# Jira config
project: cayago

# Google Document
document_id: 1_g2pytVCC179HOrh5h5ommWdvYrRitb04Z_zJFT-0Ag
dates:
    start_date: 2023-05-03
    end_date: 2023-05-07

# Style
style:
    text_size:
        small: 12
        big: 30