# Jira config
project: cayago

# Google Document
document_id: 17yaE2CV4JOGChBTBAn2YfJjYU_7lYyen5G2yZwngW64
dates:
    start_date: 2023-05-03
    end_date: 2023-05-07

# Style
style:
    text_size:
        small: 12
        big: 30