[jira]
# Jira configuration
project = "cayago"
task_weekly_report_field = "customfield_10186"
epic_weekly_report_field = "customfield_10191"
epic_order_field = "customfield_10192"

[doc]
# Google doc configuration
document_id = "17yaE2CV4JOGChBTBAn2YfJjYU_7lYyen5G2yZwngW64"
start_date = "2023-05-03"
end_date = "2023-05-07"

[style]

[style.colors]
# Styles for the text

[style.table]
