[jira]
# Jira configuration
project = "cayago"
task_weekly_report_field = "customfield_10186"
epic_weekly_report_field = "customfield_10191"
epic_order_field = "customfield_10192"

[doc]
# Google doc configuration
document_id = "1siFRMYiPS2NlVPjZNXbcKXo93hypZJP-jMg-asSWNcA"
start_date = "2023-06-02"
end_date = "2023-06-08"

[style]

[style.colors]
# Styles for the text

[style.table]
